### ISSUE TITLE
Track for constraint not found error

### ISSUE THREAD

**Issue by monsieur42** [Uberi/MotionTracking#1]
Hi! I got this error, but at the follow track constraint the Track property is set at all of the empties.
I have windows 10. I have tried it with Blender 2.74, 2.75 and 2.76. I have changed all file paths to normal characters.

> Traceback (most recent call last):
>   File "C:\Users\Miklós\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\Resolve Camera Tracks.py", line 34, in execute
>     track, _ = self.get_target_track(target)
>   File "C:\Users\Miklós\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\Resolve Camera Tracks.py", line 75, in get_target_track
>     raise Exception("Track for constraint \"{}\" of \"{}\" not found".format(track_constraint, target.name))
> Exception: Track for constraint "<bpy_struct, FollowTrackConstraint("Follow Track")>" of "boka.001" not found
> 
> location: <unknown location>:-1 "

**Comment by Uberi** [comment]
Hi @monsieur42,

Sorry, I missed this issue in my feed. Would you mind uploading a blend file that exhibits this issue?

Does the example scene work correctly?

**Comment by monsieur42** [comment]
No the example file do the same error.

**Comment by Uberi** [comment]
Do you have a blend file that makes the error happen? If so, could you upload it to http://www.pasteall.org/blend/ and link it back here?

**Comment by monsieur42** [comment]
Hey! Sorry for disappearing for month. I was really busy. Here is a blend file that makes the error. This is the example file I have just deleted the sword and the result empties of resolving. When I select emties linked to the tracks and click on "Resolve Camera Tracks" it shows the error message above.

http://www.pasteall.org/blend/40949

**Comment by monsieur42** [comment]
I have just found the problem! The error comes only if the tracks are linked to an object at the Movie Clip Editor. If I create all the all the tracks under the Camera than it works fine! Is it the correct behavior for the plugin?

**Comment by Uberi** [comment]
Hi @monsieur42,

Glad you managed to solve it! Ideally the plugin should give a warning or work in that scenario, so I'll look into that. Thanks for reporting.

**Comment by Uberi** [comment]
This should now be fixed as of 9223b253af866e0c5551d748910dfcf91f608a81. Please re-open if issues persist.

**Comment by monsieur42** [comment]
Awesome! Thanks a lot! :)
